### ISSUE TITLE
Issue: Not compatible with Custom User Model (without username) 

### ISSUE THREAD

**Issue by abriemme** [synw/django-instant#26]
On `instant.token.py` `Exception Value: 'User' object has no attribute 'username'`

I rely on a custom User with email instead of username with `USERNAME_FIELD = 'email'` set on the User class.
`AbstractBaseUser.get_username` is better suited
https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser.get_username

```
Traceback (most recent call last):
  File "/Users/maximeabry/.pyenv/versions/3.8.14/envs/.../lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/maximeabry/.pyenv/versions/3.8.14/envs/orderoom/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/maximeabry/.pyenv/versions/3.8.14/envs/orderoom/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/maximeabry/.pyenv/versions/3.8.14/envs/orderoom/lib/python3.8/site-packages/instant/views.py", line 77, in get_connection_token
    return _get_response(request)
  File "/Users/maximeabry/.pyenv/versions/3.8.14/envs/orderoom/lib/python3.8/site-packages/instant/views.py", line 42, in _get_response
    "ws_token": connection_token(request.user),
  File "/Users/maximeabry/.pyenv/versions/3.8.14/envs/orderoom/lib/python3.8/site-packages/instant/token.py", line 11, in connection_token
    claims = {"sub": user.username, "exp": int(time.time()) + 24 * 60 * 60}
  File "/Users/maximeabry/.pyenv/versions/3.8.14/envs/orderoom/lib/python3.8/site-packages/django/utils/functional.py", line 268, in inner
    return func(_wrapped, *args)

Exception Type: AttributeError at /instant/get_token/
Exception Value: 'User' object has no attribute 'username'
```

**Comment by synw** [comment]
@abriemme thanks: I merged your PR and I am preparing a release that will include your fix
